import {describe,it,expect} from 'vitest';
import {hazardVaporPose,resolutionFragmentPose,workfaceResolutionAction} from '../src/ui/survivors-hazard-animation';
import {industrialHazardArtwork} from '../src/ui/survivors-industrial-art';
import type {Hazard} from '../src/domain/patrol-survivors';
import {WORKFACE_THREATS} from '../src/ui/survivors-workface-threats';
import {WORKFACE_SPECIES} from '../src/engine/survivors-workface-roster';
describe('authored monster animation and death continuity',()=>{
 it('uses the same regional source for a live and cleared monster, preserving designated bosses',()=>{const base={naturalWidth:256} as HTMLImageElement,regional={naturalWidth:512} as HTMLImageElement,threat={naturalWidth:256} as HTMLImageElement,boss={naturalWidth:256} as HTMLImageElement;const h:Hazard={id:'hazard_1',type:'RUNAWAY_CART',species:'forklift',x:0,y:0,hp:10,maxHp:10,radius:18,speed:10,damage:1,expValue:1};const live=industrialHazardArtwork(base,h,'factory','surface_logistics',0,boss,undefined,threat,1,regional),cleared=industrialHazardArtwork(base,{...h,hp:0},'factory','surface_logistics',0,boss,undefined,threat,1,regional);expect(live?.source).toBe(regional);expect(cleared?.sourceCell).toBe(live?.sourceCell);expect(cleared?.size).toBe(live?.size);expect(industrialHazardArtwork(base,{...h,isStageBoss:true},'factory','surface_logistics',0,boss,undefined,threat,1,regional)?.source).toBe(boss);});
 it('maps all fifty regional identities to their visible physical material',()=>{const base={naturalWidth:256} as HTMLImageElement,regional={naturalWidth:512} as HTMLImageElement;for(const row of WORKFACE_THREATS){const h:Hazard={id:'hazard_1',type:row.type as Hazard['type'],x:0,y:0,hp:0,maxHp:100,radius:20,speed:0,damage:0,expValue:0};const art=industrialHazardArtwork(base,h,'factory','surface_logistics',0,undefined,undefined,undefined,row.stage,regional);expect(art?.sourceCell).toBe(row.cell);expect(art?.action).toBe(workfaceResolutionAction(h.type,row.subject));if(h.type==='GAS_LEAK')expect(art?.placement.solid).toBe(false);}expect(workfaceResolutionAction('FALLING_DEBRIS','one aluminum formwork panel')).toBe('ring');expect(workfaceResolutionAction('FALLING_DEBRIS','red broken bricks')).toBe('crumble');});
 it('keeps plume flow bounded and deterministic, and ties pulse pressure to the real warning',()=>{const h={id:'hazard_1',variant:'pulse_gas' as const};const before=JSON.stringify(h);for(let t=0;t<10;t+=.1)for(let i=0;i<3;i++){const p=hazardVaporPose(h,t,i);expect(p.alpha).toBeGreaterThanOrEqual(0);expect(p.alpha).toBeLessThanOrEqual(.22);expect(p.y).toBeGreaterThan(-.24);expect(p.scale).toBeLessThan(.4);expect(p).toEqual(hazardVaporPose(h,t,i));}expect(JSON.stringify(h)).toBe(before);expect(hazardVaporPose({...h,motion:{phase:'warning',timer:.3,directionX:0,directionY:0}},1,0).x).toBeCloseTo(hazardVaporPose(h,1,0).x*1.25);});
 it('separates fragment trajectories, settles them and fixes all reduced-motion geometry',()=>{for(const species of WORKFACE_SPECIES){const a=resolutionFragmentPose(species,.25,0),b=resolutionFragmentPose(species,.25,5);expect(a).not.toEqual(b);for(let age=0;age<2;age+=.05)for(let i=0;i<6;i++){const p=resolutionFragmentPose(species,age,i);expect(Math.abs(p.x)).toBeLessThan(24);expect(Math.abs(p.y)).toBeLessThan(25);expect(Math.abs(p.angle)).toBeLessThan(.31);}expect(resolutionFragmentPose(species,2,1)).toEqual(resolutionFragmentPose(species,3,1));expect(resolutionFragmentPose(species,.25,0,true)).toEqual({x:0,y:0,angle:0});}});
});
