import {describe,it,expect} from 'vitest';
import {SurvivorsEngine,createInitialSurvivorsState,EVOLUTION_RECIPES} from '../src/engine/patrol-survivors-engine';
import type {EvolutionPerkId} from '../src/domain/patrol-survivors';
import {operationHandoff} from '../src/domain/survivors-operation-handoff';
describe('isolated equipment simulation and campaign handoff',()=>{
 it('uses real growth tuning and never mutates the source run',()=>{const source=createInitialSurvivorsState(),before=JSON.stringify(source);const e=SurvivorsEngine.equipmentPreview(source,'radio_boost',5);const kinds=new Set<string>();for(let i=0;i<180;i++){e.advanceEquipmentPreview(1/60);for(const p of e.drainProjectileFeedback())kinds.add(p.kind);}expect(kinds.has('radio')).toBe(true);expect(e.state.activePerks.radio_boost).toBe(5);expect(JSON.stringify(source)).toBe(before);});
 it('gives every evolution its real recipe and finite projectiles',()=>{for(const id of Object.keys(EVOLUTION_RECIPES) as EvolutionPerkId[]){const e=SurvivorsEngine.equipmentPreview(createInitialSurvivorsState(),id,1);for(let i=0;i<240;i++)e.advanceEquipmentPreview(1/60);expect(e.state.activePerks[id]).toBe(1);expect(e.state.activePerks[EVOLUTION_RECIPES[id].weapon]).toBe(5);expect(e.state.projectiles.length).toBeLessThan(150);expect(e.state.projectiles.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))).toBe(true);}});
 it('tests shield absorption only in an isolated preview',()=>{const source=createInitialSurvivorsState('player',undefined,undefined,undefined,{owned:['shock_mantle'],equipped:['shock_mantle']});const before=JSON.stringify(source);const e=SurvivorsEngine.equipmentPreview(source,'radio_boost',1),shield=e.state.premiumGear!.shield;expect(e.previewEquipmentDefense()).toBe(true);expect(e.state.premiumGear!.shield).toBeLessThan(shield);expect(e.state.player.hp).toBe(e.state.player.maxHp);expect(JSON.stringify(source)).toBe(before);expect(new SurvivorsEngine(source).previewEquipmentDefense()).toBe(false);});
 it('cannot advance a production engine using the preview method',()=>{const e=new SurvivorsEngine();const before=JSON.stringify(e.state);e.advanceEquipmentPreview(.05);expect(JSON.stringify(e.state)).toBe(before);});
 it('records actual results with the selected character and copies stars',()=>{const s=createInitialSurvivorsState('kang_taesik');expect(operationHandoff(s)).toBeNull();s.phase='victory';s.terrainRecord!.rubbleCleared=2;const report=operationHandoff(s)!;expect(report.characterId).toBe('kang_taesik');expect(report.rubbleCleared).toBe(2);s.starsEarned[0]=true;expect(report.stars[0]).toBe(false);});
});
