// @vitest-environment jsdom
// These flow fixtures omit network image loading; readiness is verified in browser QA.
vi.mock('../src/ui/use-prepared-survivors-actor',()=>({usePreparedSurvivorsActor:(selected:string)=>selected}));
import {act} from 'react';
import {createRoot} from 'react-dom/client';
import {afterEach,expect,it,vi} from 'vitest';
import {PatrolSurvivorsGame} from '../src/ui/PatrolSurvivorsGame';
import {SurvivorsEngine} from '../src/engine/patrol-survivors-engine';
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();localStorage.clear();});
it('locks pause shortcuts behind wave supply and resumes only on completion',()=>{
 let frame:FrameRequestCallback=()=>{},engine!:SurvivorsEngine;
 vi.stubGlobal('requestAnimationFrame',(callback:FrameRequestCallback)=>{frame=callback;return 1;});vi.stubGlobal('cancelAnimationFrame',vi.fn());
 const ctx=new Proxy({}, {get:(_,key)=>key==='createLinearGradient'||key==='createRadialGradient'?()=>({addColorStop:vi.fn()}):key==='measureText'?()=>({width:10}):vi.fn(),set:()=>true});
 vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue(ctx as CanvasRenderingContext2D);
 const start=SurvivorsEngine.prototype.start;
 vi.spyOn(SurvivorsEngine.prototype,'start').mockImplementation(function(this:SurvivorsEngine){engine=this;start.call(this);});
 const host=document.createElement('div'),root=createRoot(host);document.body.append(host);
 const click=(text:string)=>act(()=>[...host.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent?.includes(text))!.click());
 try{
  act(()=>root.render(<PatrolSurvivorsGame onExit={()=>{}} audioMuted/>));click('시그널 워치 시작');
  engine.state.gameTime=100;
  const update=vi.spyOn(engine,'update').mockImplementation(()=>{});
  act(()=>frame(performance.now()+16));
  expect(host.querySelector<HTMLButtonElement>('.survivors-pause-command')?.disabled).toBe(true);
  expect(host.querySelector('.survivors-modal-title')?.textContent).not.toBe('일시 정지');
  for(const code of ['KeyP','Escape'])act(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code})));
  expect(engine.state.phase).toBe('paused');expect(engine.state.gameTime).toBe(100);
  click('정비 완료 · 순찰 재개');expect(engine.state.phase).toBe('playing');
  update.mockRestore();act(()=>frame(performance.now()+50));
  expect(engine.state.gameTime).toBeGreaterThan(100);
  expect(host.textContent).not.toContain('정비 완료 · 순찰 재개');
 }finally{act(()=>root.unmount());host.remove();}
});
it('pauses live purchases, applies gear without restarting, blocks resume keys, and settles wear/reward once',()=>{
 localStorage.setItem('psi.survivors.store_wallet',JSON.stringify({credits:10000,inventory:{owned:['voice_lens'],equipped:['voice_lens']}}));
 let frame:FrameRequestCallback=()=>{},engine!:SurvivorsEngine;
 vi.stubGlobal('requestAnimationFrame',(callback:FrameRequestCallback)=>{frame=callback;return 1;});vi.stubGlobal('cancelAnimationFrame',vi.fn());
 const ctx=new Proxy({}, {get:(_,key)=>key==='createLinearGradient'||key==='createRadialGradient'?()=>({addColorStop:vi.fn()}):key==='measureText'?()=>({width:10}):vi.fn(),set:()=>true});
 vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue(ctx as CanvasRenderingContext2D);
 const start=SurvivorsEngine.prototype.start;
 vi.spyOn(SurvivorsEngine.prototype,'start').mockImplementation(function(this:SurvivorsEngine){engine=this;start.call(this);});
 const host=document.createElement('div'),root=createRoot(host);
 document.body.append(host);
 const click=(text:string)=>act(()=>[...host.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent?.trim()===text)!.click());
 const tick=()=>act(()=>frame(performance.now()+16));
 try{
  act(()=>root.render(<PatrolSurvivorsGame onExit={()=>{}} audioMuted/>));click('시그널 워치 시작');
  engine.state.player.hp=40;engine.state.gameTime=100;
  vi.spyOn(engine,'update').mockImplementation(()=>{});
  tick();tick();
  expect(engine.state.psiCredits).toBe(120);
  expect(JSON.parse(localStorage.getItem('psi.survivors.store_wallet')!).credits).toBe(10120);
  act(()=>host.querySelector<HTMLButtonElement>('.shop-continue-btn')!.click());
  act(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyP'})));
  click('PSI 장비실');expect(engine.state.phase).toBe('paused');
  act(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyP'})));expect(engine.state.phase).toBe('paused');
  const mantle=[...host.querySelectorAll('article')].find(card=>card.textContent?.includes('충격 흡수 맨틀'))!;
  act(()=>mantle.querySelector<HTMLButtonElement>('button')!.click());
  expect(JSON.parse(localStorage.getItem('psi.survivors.store_wallet')!).credits).toBe(4920);
  act(()=>mantle.querySelector<HTMLButtonElement>('button')!.click());
  expect(engine.state.premiumGear?.equipped).toEqual(['voice_lens','shock_mantle']);
  expect(engine.state.player.maxHp).toBe(120);expect(engine.state.player.hp).toBe(40);expect(engine.state.gameTime).toBe(100);
  const health=host.querySelector('[role="progressbar"][aria-label="안전 체력"]')!;
  expect(health.getAttribute('aria-valuenow')).toBe('40');expect(health.getAttribute('aria-valuemax')).toBe('120');
  act(()=>host.querySelector<HTMLButtonElement>('[aria-label="장비실 닫기"]')!.click());expect(engine.state.phase).toBe('paused');
  click('순찰 재개');expect(engine.state.phase).toBe('playing');
  engine.state.gameTime=110;tick();tick();
  expect(engine.state.psiCredits).toBe(300);
  expect(JSON.parse(localStorage.getItem('psi.survivors.store_wallet')!).credits).toBe(5100);
  act(()=>host.querySelector<HTMLButtonElement>('.shop-continue-btn')!.click());
  vi.spyOn(engine,'update').mockImplementation(()=>{engine.state.phase='victory';engine.state.psiCredits=350;engine.state.starsEarned=[true,false,false];});
  tick();tick();tick();
  const wallet=JSON.parse(localStorage.getItem('psi.survivors.store_wallet')!);
  expect(wallet.credits).toBe(5150);expect(wallet.inventory.durability).toEqual({voice_lens:85,shock_mantle:85});
  expect(host.querySelector('.survivors-clear-maintenance')?.textContent).toContain('85/100');
  const dialog=host.querySelector<HTMLElement>('[role="dialog"][aria-labelledby="survivors-result-title"]')!;
  expect(dialog.getAttribute('aria-modal')).toBe('true');
  const actions=dialog.querySelectorAll<HTMLButtonElement>('.survivors-result-actions button');
  expect(document.activeElement).toBe(actions[0]);
  actions[actions.length-1]!.focus();
  act(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true})));
  expect(document.activeElement).toBe(dialog.querySelector('.survivors-result-body'));
  act(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true})));
  expect(document.activeElement).toBe(actions[actions.length-1]);
  expect(host.querySelectorAll('.survivors-result-reward')).toHaveLength(1);
  expect(host.querySelector('.survivors-result-reward strong')?.textContent).toBe('+350 PSI');
  expect(host.querySelector('.survivors-results-grid')?.textContent).toContain('보완 인계');
  const starts=vi.mocked(SurvivorsEngine.prototype.start).mock.calls.length;
  click('같은 작전 다시 준비');
  expect(vi.mocked(SurvivorsEngine.prototype.start).mock.calls.length).toBe(starts);
  expect(host.textContent).toContain('시그널 워치 시작');
  expect(JSON.parse(localStorage.getItem('psi.survivors.store_wallet')!).credits).toBe(5150);
 }finally{act(()=>root.unmount());host.remove();}
});
